// titleToCategory.js (versi ESM)
const categories = [
  {
    name: '📽️ Multimedia & Editing',
    priority: 3,
    keywords: [
      'ai',
      'audio',
      'codec',
      'convert',
      'cut',
      'durasi',
      'ffmpeg',
      'film',
      'format',
      'foto',
      'gabung',
      'gambar',
      'ghostscript',
      'imagemagick',
      'kompres',
      'mp3',
      'multimedia',
      'ogg',
      'pdf',
      'pdftk',
      'potong',
      'rekam',
      'resize',
      'scan',
      'split',
      'video',
      'vlc',
      'watermark',
    ],
  },
  {
    name: '🐧 Linux & Open Source',
    priority: 5,
    keywords: [
      'apt',
      'arch',
      'blankon',
      'chroot',
      'compiz',
      'conky',
      'debian',
      'desktop',
      'distro',
      'dpkg',
      'fedora',
      'foss',
      'gnome',
      'grub',
      'kde',
      'komunitas',
      'kpli',
      'libreoffice',
      'linux',
      'live usb',
      'lts',
      'mirror',
      'nixos',
      'openoffice',
      'open source',
      'opensuse',
      'oss',
      'perl',
      'repo',
      'rsync',
      'slackware',
      'ubuntu',
      'ubuntu party',
      'yum',
    ],
  },
  {
    name: '📚 Islam & Kehidupan',
    priority: 4,
    keywords: [
      'akidah',
      'aqidah',
      'doa',
      'fiqh',
      'fitnah',
      'ghibah',
      'hadis',
      'halal',
      'haram',
      'hijab',
      'hijriyah',
      'hukum',
      'imam',
      'iman',
      'islam',
      'istigfar',
      'istighfar',
      'janji',
      'madinah',
      'masjid',
      'maulid',
      'mukjizat',
      'mushaf utsman',
      'muslim',
      'nabi',
      'piagam madinah',
      'qunut',
      'quran',
      'ramadhan',
      'risalah',
      'sabar',
      'salam',
      'shalat',
      'sombong',
      'syariat',
      'tabut',
    ],
  },
  {
    name: '🏞️ Budaya, Kuliner & Lifestyle',
    priority: 2,
    keywords: [
      'angkringan',
      'bahagia',
      'bali',
      'bandara',
      'bekapai',
      'camilan',
      'hotel',
      'jagung',
      'jogja',
      'kerupuk',
      'kesehatan',
      'kopi',
      'kuliner',
      'kurma',
      'minuman',
      'obat',
      'pecel',
      'psikotes',
      'respiro',
      'sakit',
      'tidur',
      'wanita',
      'wisata',
    ],
  },
  {
    name: '📰 Catatan & Sosial',
    priority: 1,
    keywords: [
      'aturan',
      'bisnis',
      'catatan',
      'cuti',
      'duit',
      'ekspedisi',
      'fenomena',
      'golput',
      'harian',
      'ibu',
      'indonesia',
      'kerja halal',
      'kopdar',
      'kota',
      'kreativitas',
      'nostalgia',
      'pekerjaan',
      'peradaban',
      'perencanaan',
      'perjalanan',
      'perusahaan',
      'ppdb',
      'produktifitas',
      'pt',
      'rencana',
      'renungan',
      'sahabat',
      'sejarah',
      'sktm',
    ],
  },
  {
    name: '💻 Windows & Teknologi Umum',
    priority: 3,
    keywords: [
      'amd',
      'baterai',
      'bootloader',
      'cooling',
      'cpu',
      'eula',
      'git',
      'github',
      'hdd',
      'jaringan',
      'keyring',
      'laptop',
      'learning',
      'lisensi',
      'mic',
      'optimasi',
      'osborne1',
      'phishing',
      'piracy',
      'refresh',
      'samba',
      'shutdown',
      'software',
      'ssd',
      'terminal',
      'virtualbox',
      'wifi',
      'windows',
    ],
  },
]

export function titleToCategory(title) {
  const t = title.toLowerCase()
  let bestMatch = { name: '🗂️ Lainnya', score: 0, priority: 0 }

  for (const cat of categories) {
    let score = 0
    for (const k of cat.keywords) {
      const regex = new RegExp(`\\b${k}\\b`, 'i') // match kata utuh
      if (regex.test(t)) {
        score++
      }
    }

    if (
      score > bestMatch.score ||
      (score === bestMatch.score && cat.priority > bestMatch.priority)
    ) {
      bestMatch = { name: cat.name, score, priority: cat.priority }
    }
  }

  return bestMatch.name
}
