name: kirim konten

on:
  push:
    branches: ["main"]
    paths:
      - "artikelx/*.html"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  modify-html-then-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Jalankan inject-meta.js
        run: node ext/inject-meta.js   # ⬅️ sekarang dipanggil dari ext/

      - name: Sisipkan <!-- prettier-ignore --> sebelum <title>
        run: |
          for file in artikelx/*.html; do
            if grep -q "<!-- prettier-ignore -->" "$file"; then
              echo "ℹ️ Sudah ada prettier-ignore di $file"
              continue
            fi
            perl -0777 -i -pe 's|<title>(.*?)</title>|<!-- prettier-ignore -->\n<title>\1</title>|is' "$file"
            echo "✅ Ditambahkan prettier-ignore di $file"
          done

      - name: Sisipkan <meta name="date"> & Google Verification
        run: |
          for file in artikelx/*.html; do
            # Meta Date
            if grep -qi '<meta[^>]*name="date"' "$file"; then
              echo "ℹ️ Sudah ada meta date di $file"
            else
              DATE=$(git log --follow --format=%aI -- "$file" | tail -1)
              [ -z "$DATE" ] && DATE=$(date -u +"%Y-%m-%d") || DATE=$(date -d "$DATE" +"%Y-%m-%d")
              sed -i "/<\/head>/i <meta name=\"date\" content=\"$DATE\">" "$file"
              echo "✅ Ditambahkan meta date $DATE di $file"
            fi

            # Google Site Verification
            if grep -qi 'google-site-verification' "$file"; then
              echo "ℹ️ Sudah ada google-site-verification di $file"
            else
              sed -i "/<\/head>/i <meta name=\"google-site-verification\" content=\"9Jwla8V71mwNNZ4NNPThsK_BHpWn6quXWSs_VjPAflA\" />" "$file"
              echo "✅ Ditambahkan google-site-verification di $file"
            fi

            # related.css
            if grep -qi '/ext/related.css' "$file"; then
              echo "ℹ️ Sudah ada ext/related.css di $file"
            else
              sed -i '/<\/head>/i <link rel="stylesheet" href=\"/ext/related.css\">' "$file"
              echo "✅ Ditambahkan ext/related.css di $file"
            fi

            # Toggle button
            if grep -qi '>❌</button>' "$file"; then
              echo "ℹ️ Sudah ada toggle ❌ di $file"
            else
              sed -i '/<\/body>/i <button id="related-posts-toggle">❌</button>' "$file"
              echo "✅ Ditambahkan toggle ❌ di $file"
            fi

            # Related posts container
            if grep -qi 'related-posts-container' "$file"; then
              echo "ℹ️ Sudah ada related-posts-container di $file"
            else
              sed -i '/<\/body>/i <div id="related-posts-container">' "$file"
              echo "✅ Ditambahkan related-posts-container di $file"
            fi

            # Related posts list
            if grep -qi 'related-posts-list' "$file"; then
              echo "ℹ️ Sudah ada related-posts-list di $file"
            else
              sed -i '/<\/body>/i <ul id="related-posts-list"></ul></div>' "$file"
              echo "✅ Ditambahkan related-posts-list di $file"
            fi

            if grep -qi '/ext/related.js' "$file"; then
              echo "ℹ️ Sudah ada skrip related di $file"
            else
              sed -i '/<\/body>/i <script src="/ext/related.js"></script>' "$file"
              echo "✅ Ditambahkan skrip related di $file"
            fi
          done
    
      - name: Pindahkan file HTML ke folder artikel/
        run: |
          mkdir -p artikel
          mv -f artikelx/*.html artikel/ || true

      - name: Commit & Push perubahan
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if git diff --quiet; then
            echo "Tidak ada perubahan baru, skip commit."
          else
            git add artikelx || true
            git add artikel || true
            git commit -m "modif di artikelx/ lalu pindahin ke artikel/"
            git push
          fi
