name: Ganti URL Artikel ke Image dan Buat PR

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: 'Folder yang ingin diproses (misalnya: docs/html)'
        required: true
        default: '.'

jobs:
  ubah-url-dan-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Buat branch baru
        run: |
          BRANCH_NAME=ubah-url-artikel-ke-img-$(date +%s)
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Ganti URL artikel → image untuk .jpg
        run: |
          find "${{ github.event.inputs.target_folder }}" -type f -name "*.html" \
            -exec sed -i 's|https://frijal\.pages\.dev/artikel/\([^"]*\.jpg\)|https://frijal.pages.dev/img/\1|g' {} +

      - name: Commit perubahan
        run: |
          git add .
          git commit -m "Ganti URL artikel → img untuk .jpg"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Buat Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Ganti URL artikel → image untuk .jpg"
          body: |
            Perubahan otomatis:
            - Mengganti URL `https://frijal.pages.dev/artikel/*.jpg` menjadi `https://frijal.pages.dev/img/*.jpg`
            - Folder yang diproses: `${{ github.event.inputs.target_folder }}`
