name: Generate JSON & Sitemap

on:
  push:
    branches:
      - main
    paths:
      - 'artikel/**'     # hanya jalan kalau ada perubahan di folder artikel/
  schedule:
    - cron: "0 0 * * *"   # jalan otomatis tiap tengah malam UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm init -y
          npm install jsdom

      - name: Generate artikel.json & sitemap.xml
        run:  node ext/generate.js
          
          # --- Perbandingan dengan artikel.json lama ---
          let oldData = {};
          if (fs.existsSync("artikel.json")) {
            try {
              oldData = JSON.parse(fs.readFileSync("artikel.json","utf-8"));
            } catch {}
          }

          const newData = grouped;
          const changes = {added:[], removed:[], updated:[]};

          # cari yang baru ditambahkan
          for (const [cat, arts] of Object.entries(newData)) {
            arts.forEach(([title,file])=>{
              const existed = Object.values(oldData).flat().some(([t,f])=>t===title && f===file);
              if (!existed) changes.added.push(`${title} (${file})`);
            });
          }

          # cari yang dihapus
          for (const [cat, arts] of Object.entries(oldData)) {
            arts.forEach(([title,file])=>{
              const stillExists = Object.values(newData).flat().some(([t,f])=>t===title && f===file);
              if (!stillExists) changes.removed.push(`${title} (${file})`);
            });
          }

          # log perubahan
          console.log("📊 Perubahan artikel:");
          if (changes.added.length) console.log("➕ Ditambahkan:", changes.added.join(", "));
          if (changes.removed.length) console.log("➖ Dihapus:", changes.removed.join(", "));
          if (!changes.added.length && !changes.removed.length) console.log("ℹ️ Tidak ada perubahan pada artikel.");

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add artikel.json sitemap.xml
          git diff --cached --quiet || git commit -m "Auto-generate artikel.json & sitemap.xml"
          git push

      - name: Ping Google & Bing with retry
        run: |
          echo "🔔 Pinging search engines..."
          for TRY in 1 2; do
            STATUS_GOOGLE=$(curl -o /dev/null -s -w "%{http_code}" "https://www.google.com/ping?sitemap=https://frijal.github.io/sitemap.xml")
            STATUS_BING=$(curl -o /dev/null -s -w "%{http_code}" "https://www.bing.com/ping?sitemap=https://frijal.github.io/sitemap.xml")
            echo "Attempt $TRY - Google status: $STATUS_GOOGLE | Bing status: $STATUS_BING"

            if [ "$STATUS_GOOGLE" = "200" ] && [ "$STATUS_BING" = "200" ]; then
              echo "✅ Ping sukses ke Google & Bing"
              exit 0
            fi

            if [ "$TRY" -eq 1 ]; then
              echo "⚠️ Ping gagal, coba ulang dalam 30 detik..."
              sleep 30
            fi
          done

          echo "❌ Ping Google/Bing tetap gagal setelah 2 percobaan"
          exit 1

      - name: Telegram notification
        if: failure()
        run: |
          MSG="❌ Sitemap ping gagal di repo $GITHUB_REPOSITORY (workflow: $GITHUB_WORKFLOW)"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG"
