name: RSS Feed Atom

on:
  push:
    paths:
      - 'artikel.json'
      - 'sitemap.xml'
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run rss.js
        run: node ext/rss.js
        env:
          RSS_LIMIT: 30

      - name: Copy rss.xml to alias feeds
        run: |
          cp rss.xml rss
          cp rss.xml atom
          cp rss.xml feed

      - name: Commit and Push results (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add rss.xml rss atom feed || true
          git commit -m "🔄 Update RSS feed (auto)" || echo "No changes to commit"

          git fetch origin main
          git rebase origin/main || {
            echo "⚠️ Konflik saat rebase, auto-resolve dengan hasil generator (ours)"
            git rebase --abort
            git merge -X ours origin/main
          }

          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
