# .github/workflows/cleanup-orphan-images.yml
name: Pembersihan Gambar Orphan

on:
  schedule:
    # Setiap hari pukul 06:00 WITA (22:00 UTC hari sebelumnya)
    - cron: '0 22 * * *'
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  cleanup_images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cari dan Hapus Gambar Orphan
        id: cleanup
        run: |
          echo "🧹 Memulai proses pembersihan gambar Orphan..."
          DELETED_COUNT=0

          # Loop semua file .webp di img/
          for webp_file in img/*.webp; do
            [ -e "$webp_file" ] || continue

            base_name=$(basename "$webp_file" .webp)
            html_file="artikel/${base_name}.html"

            if [ ! -f "$html_file" ]; then
              echo "-> Orphan: '$webp_file' tidak memiliki artikel '$html_file'. Menghapus..."
              git rm "$webp_file"
              DELETED_COUNT=$((DELETED_COUNT + 1))
            fi
          done

          echo "✅ Proses selesai. Total file yang dihapus: $DELETED_COUNT."
          echo "deleted_count=$DELETED_COUNT" >> $GITHUB_OUTPUT

      - name: Commit Hasil Pembersihan
        if: steps.cleanup.outputs.deleted_count != '0'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            chore(cleanup): Hapus ${{ steps.cleanup.outputs.deleted_count }} gambar orphan
            Membersihkan file .webp di folder /img yang tidak lagi memiliki
            file .html yang sesuai di folder /artikel.
          branch: ${{ github.ref_name }}
          file_pattern: img/*.webp
