name: Remove Custom Text and Create PR (PAT Ready)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Teks/Tag yang ingin dihapus (contoh: <h3>Artikel Terkait</h3>)'
        required: true
        default: 'ketik apa yang mau dihapus?'
      folder:
        description: 'Folder target tempat file .html berada'
        required: true
        default: 'artikel'

permissions:
  contents: write
  pull-requests: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Remove target text from folder
        run: |
          TARGET="${{ github.event.inputs.target }}"
          FOLDER="${{ github.event.inputs.folder }}"
          echo "📂 Target folder: $FOLDER"
          echo "✂️ Menghapus: $TARGET"

          if [ -d "$FOLDER" ]; then
            find "$FOLDER" -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
              echo "   ↳ Edit $file"
              sed -i "s|$TARGET||g" "$file"
            done
          else
            echo "⚠️ Folder $FOLDER tidak ditemukan!"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          commit-message: "Remove text from ${{ github.event.inputs.folder }}/*.html"
          branch: remove-text
          branch-suffix: timestamp
          title: "Remove text from ${{ github.event.inputs.folder }}/*.html"
          body: |
            This PR removes the following text from all HTML files in `${{ github.event.inputs.folder }}/`:

            ```
            ${{ github.event.inputs.target }}
            ```

            ✅ Auto-generated by GitHub Actions
