name: 🧩 Proses ArtikelX lalu Pindahkan ke Artikel

on:
  push:
    branches: ['main']
    paths:
      - 'artikelx/*.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process_and_move_articles:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧩 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ====================== MODIFIKASI FILE DI artikelx/ ======================
      - name: 1️⃣ Jalankan Perl find-and-replace
        run: |
          for file in artikelx/*.html; do
            echo "Memproses find-and-replace pada $file"
            perl -pi -w -e 's#https://frijal.pages.dev/assets/apple-touch-icon.png#https://frijal.pages.dev/ext/icons/apple-touch-icon.png#g' "$file"
            perl -pi -w -e 's#YOUR_APP_ID#1471267430691023#g' "$file"
            perl -pi -w -e 's#YOUR_FACEBOOK_APP_ID#1471267430691023#g' "$file"
            perl -pi -w -e 's#nama_twitter_anda#frijal#g' "$file"
            perl -pi -w -e 's/©/🄯/g' "$file"
            perl -pi -w -e 's#href="https://frijal.pages.dev/artikel/"#href="https://frijal.pages.dev/artikel.html"#g' "$file"
          done

      - name: 2️⃣ Jalankan inject-meta.js
        run: node ext/inject-meta.js || true

      - name: 3️⃣ Tambahkan elemen HTML tambahan
        run: |
          for file in artikelx/*.html; do
            sed -i '/<\/head>/i <link rel="stylesheet" href="/ext/marquee-url.css">' "$file"
            sed -i '/<\/h1>/a <div id="iposbrowser"></div>' "$file"
            sed -i '/<\/body>/i <div class="search-floating-container"><input type="text" id="floatingSearchInput" placeholder="cari artikel..." autocomplete="off"><span id="floatingSearchClear" class="clear-button">&times;</span><div id="floatingSearchResults" class="floating-results-container"></div></div>' "$file"
            sed -i '/<\/body>/i <section id="related-marquee-section"><div id="related-marquee-container"></div></section><div id="kategori-aktif"></div><script defer src="/ext/marquee-url.js"></script>' "$file"
            sed -i '/<\/body>/i <script defer src="/ext/iposbrowser.js"></script>' "$file"
          done

      # =================== PINDAHKAN DAN COMMIT ===================
      - name: 4️⃣ Pindahkan hasil ke artikel/
        run: mv -f artikelx/*.html artikel/ || true

      - name: 5️⃣ Commit & Push hasil
        id: commit_step
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          moved_files=$(ls artikelx/*.html 2>/dev/null || true)
          if git diff --quiet && [ -z "$moved_files" ]; then
            echo "skip_commit=true" >> $GITHUB_OUTPUT
            echo "Tidak ada perubahan baru, skip commit."
          else
            git add artikel artikelx
            git commit -m "✨ Artikel baru dipindahkan dari artikelx → artikel [skip ci]"
            git push
            echo "skip_commit=false" >> $GITHUB_OUTPUT
          fi

