name: Pencarian Kata Format Terbalik

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'Kata yang ingin dicari dalam file .html'
        required: true
        default: 'metadata'

jobs:
  cari-format-terbalik:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Buat folder mini jika belum ada
        run: mkdir -p mini

      - name: Cari kata dan simpan format terbalik ke mini/hasil.txt
        run: |
          echo "Mencari kata '${{ github.event.inputs.keyword }}' di semua file .html..."
          > mini/hasil.txt
          find . -type f -name "*.html" | while read file; do
            if grep -qi "${{ github.event.inputs.keyword }}" "$file"; then
              nama=$(basename "$file")
              echo "${{ github.event.inputs.keyword }}, $nama" >> mini/hasil.txt
            fi
          done

      - name: Tampilkan isi hasil.txt
        run: cat mini/hasil.txt || echo "(Tidak ada hasil)"
