name: Update artikel.json

on:
  push:
    paths:
      - 'artikel/**'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate artikel.json
      run: |
        mkdir -p temp
        for f in artikel/*.html; do
          fname=$(basename "$f")
          title=$(basename "$f" .html | sed 's/[-_]/ /g' | sed 's/\b\(.\)/\u\1/g')
          # Tentukan kategori sederhana
          if [[ "$title" =~ [Ll]inux ]]; then category="OS/Linux"; 
          elif [[ "$title" =~ [Hh]ijab ]]; then category="Religi"; 
          else category="Lainnya"; fi
          echo "{\"title\":\"$title\",\"file\":\"$fname\",\"category\":\"$category\"}," >> temp/json.tmp
        done
        # Tambahkan kurung siku dan hapus koma terakhir
        echo "[" > artikel.json
        sed '$ s/,$//' temp/json.tmp >> artikel.json
        echo "]" >> artikel.json

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add artikel.json
        git commit -m "Update artikel.json via GitHub Actions" || echo "No changes to commit"
        git push

